config/routes.rb
Rails.application.routes.draw do
root to: 'static_pages#home'

  devise_for :users
  
  scope "/dashboard" do
    get "admin", to: "dashboard#admin", as: "dashboard_admin"
    get "student", to: "dashboard#student", as: "dashboard_student"
    get "mentor", to: "dashboard#mentor", as: "dashboard_mentor"
  end
  
  resources :dashboard, :themes, :chapters, :courses, :quizzes, :question_answers, :groups, :seasons, :memberships, :user_theme_seasons

  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'fees', to: 'static_pages#fees'
  post 'contact', to: 'static_pages#contact_form', as: 'contact_form'

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
    get "success", to: "checkout#success", as: "checkout_success"
  end

end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :theme
  has_many :courses
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :chapter
  has_one :quiz
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :users, through: :user_groups      # Users as Students > members of the group
  belongs_to :season
  belongs_to :user       #Mentor
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user

  # ActionMailer callback after "Membership" creation to:
  # - send a "welcome message" to the Student
  # - inform the Admin a new Student as subscribe a yearly membership
  after_create :membership_send
  after_create :admin_send

  def membership_send
    UserMailer.membership_email(self).deliver_now
  end

  def admin_send
    UserMailer.admin_email(self).deliver_now
  end
  
end

app/models/question_answer.rb
class QuestionAnswer < ApplicationRecord
  belongs_to :quiz
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :course
  has_many :question_answers
end

app/models/season.rb
class Season < ApplicationRecord
  belongs_to :theme
  has_many :groups
  has_many :user_seasons
  has_many :users, through: :user_seasons
  has_many :user_theme_seasons

  def is_started?
    self.start_date < Time.now()
  end
  
  def is_ended?
    self.end_date < Time.now()
  end

  def is_joinable?
    self.is_started? && !self.is_ended?
  end

  def start_in?
    days = self.start_date - Time.now()
    days.to_i / 60 / 60 / 24
  end

end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :seasons
  has_many :chapters
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:student, :mentor, :admin]
  after_initialize :set_default_role, :if => :new_record?

  has_many :user_seasons
  has_many :seasons, through: :user_seasons

  # Return the role of a given "User" object
  def what_role?
    return self.role
  end

  private

  def set_default_role
    self.role ||= :student
  end

end

app/models/user_season.rb
class UserSeason < ApplicationRecord
  belongs_to :season
  belongs_to :user 
end

app/models/users_group.rb
class UsersGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/utsc_course.rb
class UtscCourse < ApplicationRecord
  belongs_to :user_theme_season_chapter
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @future_seasons_themes = Season.where("start_date > ?", Date.today).all
    
    if user_signed_in?
      if current_user.what_role? == "student"
        membership = Membership.where(user_id:current_user.id).last 
        if !membership.nil?
          if membership.subscription_date >= Time.now() - 365.days
            @go_stripe = false
          else
            @go_stripe = true
          end
        else
          @go_stripe = true
        end
      else
        @go_stripe = false
      end
    else
      @go_stripe = false
    end #If not logged in, does nothing
  end
  
  def uikit
  end

  def about
  end

  def contact
  end

  def fees
  end

  def contact_form
    clean_params= params.permit(:first_name, :last_name, :email, :object, :message)
    UserMailer.contact_email(params[:first_name], params[:last_name], params[:email], params[:object], params[:message]).deliver_now
    redirect_to contact_path
  end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/quizes_helper.rb
module QuizesHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/static_pages/about.html.erb
<div class="container p-5">
    <div class="row">
        <div class="col-md-5 p-4">
            <%= image_tag("contact_1.jpg", alt:"Photo 1 Contact Page", width:"350") %>
        </div>
        <div class="col-md-7 pl-3">
            <div class="card-body p-5">
                <h1 class="title">A propos de <span class="text-secondary"><b>LearnIt!</b></span></h1>
                <p class="card-text">Sur la dernière décennie, le nombre d'organismes de formation et de cursus spécialisés a littéralement explosé, mettant les formations digitales ouvertes à tous sur le devant de la scène de l'apprentissage. En parallèle, leur audience a, elle aussi, été multipliée par des chiffres que beaucoup d'autres secteurs rêveraient de pouvoir afficher. Pourtant, entre les suites e-Learning d'entreprise et quelques rares alternatives un peu trop fouillées, il n'existe que très peu de plateformes faisant la part belle au peer-learning et à toute la richesse qu'il peut apporter, lorsqu'il est bien utilisé, mis en place et animé.
                C’est ainsi que nous est venu l’idée de LearnIt! : une plateforme regroupant des ressources sélectionnées par des passionnés, pour des passionnés ayant la soif d’apprendre et de transmettre.</p>
            </div>
        </div>
    </div>
    <br/>
    <div class="row">
        <div class="col-md-7 pl-3">
            <div class="card-body p-3">
                <h1 class="title">Comment ça fonctionne ?</h1>
                <p class="card-text">En vous créant un compte sur LearnIt!, vous devenez un membre de notre communauté et avez accès à une quantités de cursus et modules créés par d’autres membres et classés par catégories. Les modules pourront être édités par leur créateur afin d'avoir une richesse de contenus à jour. Chaque membre a également accès à son espace personnel (DashBoard), qui résume ses modules créés, préférés, suivis et terminés. Les membres peuvent également suggérer la modification d'un module à son créateur via un formulaire.</p>
            </div>
        </div>
        <div class="col-md-5">
            <%= image_tag("contact_2.jpg", alt:"Photo 2 Contact Page", width:"450") %>
        </div>
    </div>
</div>



<!-- Presentation of the team -->

<style>
img {
  border-radius: 5%;
}
</style>

<div class="mt-2 team">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center">
                <h1 class="title">L'équipe</h1>
            </div>
        </div>
        <br/>
        <div class="d-flex row justify-content-center">
            <div class="col-md-3">
                <div class="col-md-12">
                    <%= image_tag("wilfried.jpg", alt:"Photo Wilfried", width:"200") %>
                    <div class="">
                        <ul class="list-inline">    
                            <li class="list-inline-item">
                                <a href="https://github.com/WilfriedPaillot">
                                    <i class="text-primary bi bi-github" style="font-size:20px;"></i>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.linkedin.com/in/wilfried-paillot/">
                                    <i class="bi bi-linkedin" style="font-size:20px;"></i>
                                </a>
                            </li>   
                        </ul>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="pt-3">
                        <h5 class="title font-medium">Wilfried Paillot</h5>
                        <h6 class="subtitle"><b>The Code Gardener</b></h6>
                        <p class="text">Il cultive le code comme on chérit un bonzaï ou on bouture des orchidées rares, le fait grandir et sait tout faire pousser, en particulier du PHP, du Ruby et du Bootstrap. La légende dit qu'il peut coder des algos hyper stylés sur des arbres N-aires rien qu'en effleurant leurs feuilles.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3 m-b-30">
                <div class="row">
                    <div class="col-md-12">
                        <%= image_tag("yassine.jpg", alt:"Photo Yassine", width:"200") %>
                        <div class="">
                            <ul class="list-inline">    
                                <li class="list-inline-item">
                                    <a href="https://github.com/YAROS31">
                                        <i class="text-primary bi bi-github" style="font-size:20px;"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="https://www.linkedin.com/in/yassinerochd/">
                                        <i class="bi bi-linkedin" style="font-size:20px;"></i>
                                    </a>
                                </li>   
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="pt-3">
                            <h5 class="title font-medium">Yassine Rochd</h5>
                            <h6 class="subtitle"><b>The Cypher</b></h6>
                            <p>Notre "homme du chiffre", expert en Private Equity, en Real Estat et, à ses heures perdues, body builder émérite autant que daily coder pour le front desk des Rotschild, JP Morgan & Co. Quand il n'est pas dans les travaux de l'une de ses résidences secondaires, il se balade dans les couloirs du Corail Paris - Toulouse.</pclass=>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3  m-b-30">
                <div class="row no-gutters">
                    <div class="col-md-12 pro-pic">
                        <%= image_tag("victoria.jpg", alt:"Photo Victoria", width:"200") %>
                        <div class="">
                            <ul class="list-inline">    
                                <li class="list-inline-item">
                                    <a href="https://github.com/Vix00">
                                        <i class="text-primary bi bi-github" style="font-size:20px;"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="https://www.linkedin.com/in/victoria-fely-050587105/">
                                        <i class="bi bi-linkedin" style="font-size:20px;"></i>
                                    </a>
                                </li>   
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="pt-3">
                            <h5 class="title font-medium">Victoria Fely</h5>
                            <h6 class="subtitle"><b>The Creative</b></h6>
                            <p>Il ne manquait plus qu’une touche féminine avec la Lara Croft du design. Jumpeuse du print au digital sans jamais s’essouffler, aventurière jusqu’au bout elle n’a pas peur d’aller sur le « front ». Junior en la matière, mais motivée « as fuck » elle va cependant affronter les obstacles et tenter le tout pour le tout.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3  m-b-30">
                <div class="row no-gutters">
                    <div class="col-md-12 pro-pic">
                        <%= image_tag("student_07.jpg", alt:"Photo Jean-Baptiste", width:"200") %>
                        <div class="">
                            <ul class="list-inline">    
                                <li class="list-inline-item">
                                    <a href="https://github.com/GibbZ-78">
                                        <i class="text-primary bi bi-github" style="font-size:20px;"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="https://www.linkedin.com/in/jeanbaptistevidal/">
                                        <i class="bi bi-linkedin" style="font-size:20px;"></i>
                                    </a>
                                </li>   
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="pt-3">
                            <h5 class="title font-medium">Jean-Baptiste Vidal</h5>
                            <h6 class="subtitle"><b>The Amstrad Mastermind</b></h6>
                            <p>Il est tombé dans le code quand il était tout petit. Depuis, il n'a pas beaucoup grandi et a dû faire une désyntox' de 15 ans "no code". Depuis quelques semaines, THPix, le druide du peer-learning lui a permis de reprendre quelques lampées de prog'. Un mystérieux moussaillon aussi appelé The Librarian lui a trouvé 1 ou 2 sites de docs sympas sur Ruby Guides et, jusqu'ici, hormis quelques scaffoldings un peu trop sauvages, tout va bien.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="col-3 mx-5">
    <a href="#" data-bs-toggle="tooltip" title="Some tooltip text!">
        Haut de page <i class="bi bi-chevron-double-up text-secondary fs-6 fw-light"></i>
    </a>
    <div class="tooltip" role="tooltip">
        <div class="tooltip-arrow">
        </div>
        <div class="tooltip-inner">
            Eyes up!
        </div>
    </div>
</div>

app/views/static_pages/contact.html.erb
<!-- CONTACTS -->

<section class="row justify-content-between mb-5 p-3 m-3">

  <div class="container">
    <div class="spacer">
      <div class="row justify-content-center">
        <div class="text-center">
          <h1 class="title font-bold">Nous Contacter</h1>
          <h6 class="subtitle">Contactez nous par mail ou via le formulaire de contact pour plus d'informations.</h6>
          </br>
        </div>
      </div>        
    </div>    

    <div class="container">
      <div class="row">
        <div class="col-md-7">
          <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d10491.793210016685!2d2.3861548!3d48.8973224!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x42dbe434c3e93484!2sThe%20Hacking%20Project!5e0!3m2!1sfr!2sfr!4v1648162323383!5m2!1sfr!2sfr" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
        <div class="col-md-5">

          <form action="<%= contact_form_path %>" method="post">
            <!--<input type="hidden" name="authenticity_token" value=""> -->
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <div class="form-group mb-2">
              <label class="form-label" for="first_name">Prénom :</label>
              <input class="form-control" name="first_name" id="first_name" type="text" placeholder="Écrivez votre prénom"/>
            </div>
            <div class="form-group mb-2">
              <label class="form-label" for="last_name">Nom :</label>
              <input class="form-control" name="last_name" id="last_name" type="text" placeholder="Écrivez votre nom"/>
            </div>
            <div class="form-group mb-2">
              <label class="form-label" for="email">Mail :</label>
              <input class="form-control" name="email" id="email" type="text" placeholder="Écrivez votre adresse mail"/>
            </div>
            <div class="form-group mb-2">
              <label class="form-label" for="object">Objet :</label>
              <input class="form-control" name="object" id="object" type="text" placeholder="Écrivez l'objet de votre message"/>
            </div>
            <div class="form-group mb-3">
              <label class="form-label" for="message" >Votre message :</label>
              <input class="form-control" name="message" id="message" type="text" placeholder="Écrivez votre message"/>
            </div>
            <div class="form-group">
              <button type="submit" class="btn btn-outline-secondary">Envoyer</button>
              <button type="reset" class="btn btn-outline-primary">Effacer</button>
            </div>
          </form>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="spacer">
        <div class="align-content-between p-4 bg-secondary" style="color:white">
          <h2 class="text-center">LearnIt!</h2> 
          </br>
          <div class="container">
            <div class="row text-center m-2 mb-4">
              <div class="col-sm-12 col-lg-6 p-1">
                <p><a href=""><i class="bi bi-geo-alt-fill fs-1" style="color:white"></i></a></p>
                <span class="lead">83, Boulevard Macdonald<br>75019 - Paris</span>
              </div>
              <div class="col-sm-12 col-lg-6 p-1">
                <p><a href=""><i class="bi bi-envelope fs-1" style="color:white"></i></a></p>
                <p><a href="mailto:bonjour@thehackingproject.org?subject=Prise de contact via le site web LearnIt!&body=Nous serons ravis de répondre à toutes vos questions et réclamations dans les plus brefs délais !" class="lead">bonjour@thehackingproject.org</a></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>      

app/views/static_pages/fees.html.erb
<section class="d-flex justify-content-center">
  <div class="pricing-header p-3 mx-auto text-center">
    <h1 class="display-4 fw-normal">Tarif</h1>
    <p class="fs-5 text-muted">Nous proposons un tarif unique qui vous donne accès exclusivement pendant 1 an à toute la palette de cours orchestrée par <span class="text-secondary"><b>LearnIt!</b></span>.</p>
  </div>
</section>

<section class="row justify-content-center">
    <div class="col-md-4 text-end px-5">
      <h2>Notre politique tarifaire</h2>
      <p>Accéder quand tu le veux, à la fréquence que tu veux, au.x programme.s que tu veux :  c'est la philosophie LearnIt!.</p>
      <p>Mieux qu'un Canal+ à la demande de l'apprentissage, nous souhaitons proposer un tarif annuel unique pour tous les passionnés et ceux qui ont l'envie d'apprendre.</p>
      <p>Des solutions de financement seront mises en place très prochainement (Boursier, Pole Emploi, CPF...).</p>
    </div>  
    <div class="col-md-5">
      <div class="card rounded-3 shadow-sm">
        <div class="card-header py-3">
          <h4 class="fw-normal text-center">Tarif unique</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title text-center">399€<small class="text-muted fw-light">/an</small></h1>
          <ul class="list-unstyled mt-3 mb-4">
            <li><i class="bi bi-chevron-double-right text-secondary fs-5"></i> Accès à des ressources exclusives</li>
            <li><i class="bi bi-chevron-double-right text-secondary fs-5"></i> Membre actif d'une communauté de learning</li>
            <li><i class="bi bi-chevron-double-right text-secondary fs-5"></i> Inter-échanges grâce au peer-programming</li>
            <li><i class="bi bi-chevron-double-right text-secondary fs-5"></i> Maître de votre emploi du temps d'apprentissage</li>
          </ul>
          <%= link_to("S'inscrire",new_user_registration_path, class:"w-100 btn btn-outline-secondary btn-lg", method:"get") %>
        </div>
      </div>
    </div>
</section>



app/views/static_pages/home.html.erb
<!-- BANNER SECTION  -->
<%= render "layouts/partials/hero_banner_index" %>

<!-- STRIPE MODAL -->
<section>
  <% if @go_stripe == true %>
  
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="false">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">Accédez au paiement</h5>
          </div>
          <div class="modal-body">
            Vous allez être redirigé vers votre panier en ligne.
          </div>
          <div class="modal-footer">
            <%= link_to("finalisez votre inscription", checkout_create_path, class:"btn btn-primary btn-lg px-4 me-md-2 text-light", method:"post", remote: true) %>
          </div>
        </div>
      </div>
    </div>

    <script>
      var myModal = new bootstrap.Modal(document.getElementById("staticBackdrop"))
      myModal.show();
    </script>

  <% end %>
</section>

<!-- PRESENTATION SECTION -->
  <section class="container">
    <h1 class="orange_underline">Learn’it, en quelques mots</h1>
    
    <div class="row justify-content-between py-5">
      <div class="col-lg-3 col-md-6">
        <div class="card-1">
          <div class="card-body">
            <div class="fs-6 mb-3">
              <i class="bi bi-book-half fs-1"></i>
            </div>
            <h5 class="card-title">Apprentissage</h5>
            <p class="card-text">Apprendre par la pratique, de manière concise et explicite grâce à des expériences d’apprentissage d’autres membres de la communauté.</p>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6">
        <div class="card-2">
          <div class="card-body">
            <div class="fs-6 mb-3">
              <i class="bi bi-broadcast-pin fs-1"></i>
            </div>
            <h5 class="card-title">Communauté</h5>
            <p class="card-text">Une communauté bienveillante pour échanger et communiquer à tout moment, avec d’autres passionnés ayant les mêmes envies d’apprendre que vous.</p>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6">
        <div class="card-3">
          <div class="card-body">
            <div class="fs-6 mb-3">
              <i class="bi bi-chat-heart fs-1"></i>
            </div>  
            <h5 class="card-title">Accessible à tous</h5>
            <p class="card-text">Nos modules sont accessibles gratuitement et quand vous le souhaitez. Chaque membre peut y contribuer à sa manière et partager ses connaissances.</p>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6">
        <div class="card-4">
          <div class="card-body">
            <div class="fs-6 mb-3">
              <i class="bi bi-bookmark-star-fill fs-1"></i>
            </div>
            <h5 class="card-title">Mise en relation</h5>
            <p class="card-text">Des cursus recensant les meilleures ressources d’internet, soigneusement sélectionnées par nos membres.</p>
          </div>
        </div>
      </div>
  </div>
</section>



<!-- THEMES SECTION -->
  <section class="container">
    <h1 class="orange_underline">Nos cursus</h1>
      <div class="row justify-content-between py-5">
        <%if @future_seasons_themes%>
          <% @future_seasons_themes.each do |theme| %>
            <%= render 'layouts/partials/homepage_theme_card', theme: theme %>
          <%end%>
        <%else%>
          <div class="col-md-6 alert alert-danger">
            <p>Erreur de chargement des thèmes</p>
          </div>
        <%end%>
      </div>
      <div class="row pb-5">
        <%= link_to themes_path, class: "nav-link" do%>
          <i class="bi bi-chevron-double-right text-secondary fs-3"></i>
          <span class="text-deep_blue fs-4 align-center ms-3">Découvrez toutes nos thématiques</span> 
        <%end%>
      </div>
  </section>

<!-- PRICE SECTION -->
<section class="row justify-content-around mb-5 bg-light_pulpit">
  <div class="col-5 mx-5 my-5 p-5">
    <p class="display-5">Chez <span class="text-secondary"><b>LearnIt!</b></span>, aucune <br/> mauvaise surprise !</p>
    <p class="display-6">Un forfait mensuel <br/> pour toutes nos ressources</p>
  </div>
  <div class="col-5 mx-5 my-5 p-5"> 
    <div class="d-flex flex-column bg-primary p-3">
      <%if !user_signed_in? %>
      <div>
        <p class="text-center p-3 text-light fs-1">Tarif unique</p>

        <p class="display-5 text-center mt-2 pt-3 p-2 text-light"><b>399€ <small class="h6 text-light">/an</b></small></p>
        <p class="text-center mt-2 pb-2 text-secondary">Sans engagement !</p>
      </div>
      <div class="d-flex justify-content-center mp-1 p-3">
        <%= link_to("S'inscrire",new_user_session_path, class:"btn btn-outline-secondary btn-lg px-4 me-md-2 text-light", method:"get") %>
      </div>
    </div>
    <%elsif current_user.role != "admin"%>
      <%if !Membership.find_by(user_id: current_user.id).nil? %>  
      <div>
        <p class="text-center p-3 text-light fs-3"><%= current_user.first_name %></p>
        <p class="text-center mt-2 pb-2 text-light fs-4">Vous faites déjà parti de nos membres &#127881;</p>
        <p class="text-center mt-2 pb-2 text-light fs-4">Votre acccès illimité à <span class="orange_underline">toutes</span> nos ressources est actif jusqu'au :</p>
        <% end_sub_date = Membership.find_by(user_id: current_user.id).subscription_date+365.days %>
        <p class="display-5 text-center mt-2 pt-3 p-2 text-light"><b><%= end_sub_date.strftime('%d/%m/%Y') %></p>
      </div>
      <div class="d-flex justify-content-center mp-1 p-3">
        <%= link_to_if(Date.today == end_sub_date-7.days, "Renouveler", checkout_create_path, class:"btn btn-outline-secondary btn-lg px-4 me-md-2 text-light", method:"post", remote: true) %>
      </div>
      </div>
      <%end %>
    <%else %>
      <p class="text-center mt-2 pb-2 text-light fs-4">Bienvenue <%= current_user.last_name.upcase %> <%= current_user.first_name.capitalize %></p>
      <div class="d-flex justify-content-center mp-1 p-3">
        <%= link_to("Dashboard", dashboard_index_path, class:"btn btn-outline-secondary btn-lg px-4 me-md-2 text-light") %>
      </div>
    <%end %>
  </div>
</section>


<!-- FEEDBACKS SECTION -->
<section class="container">
  <h2 class="orange_underline">Témoignages d'alumnis</h2>

	<div class="row py-5">

	<div class="col-lg-4">
		  <div class="card">
				<div class="card-body">
					<div class="block-author">
						<div class="author-image">
              <%= image_tag("student_01.jpg", alt:"Pic Student 01", class:"rounded", width:"60") %>
						</div>
						<div class="author-info">
							<span class="d-block mt-1"><b>Jérôme Pichenot</b></span>
						</div>
					</div>
          <p class="mt-4">
            Une plateforme au-delà de mes attentes. C'est intuitif, riche, complet, je recommande !
					</p>
				</div>
		  </div>
	</div>

  <div class="col-lg-4">
			<div class="card">
				<div class="card-body">
					<div class="block-author">
						<div class="author-image">
              <%= image_tag("student_04.jpg", alt:"Pic Student 04", class:"rounded", width:"60") %>
						</div>
						<div class="author-info">
							<span class="d-block mt-1"><b>Alexandra Ginova</b></span>
						</div>
					</div>
          <p class="mt-4 line-height-1_8">
            Grâce à LearnIt! j'ai pu aboutir ma reconversion professionnelle avec succès tout en faisant mes propres choix à mon rythme.
					</p>
				</div>
			</div>
	</div>

  <div class="col-lg-4">
			<div class="card">
				<div class="card-body">
					<div class="block-author">
						<div class="author-image">
              <%= image_tag("student_05.jpg", alt:"Pic Student 05", class:"rounded", width:"60") %>
						</div>
						<div class="author-info">
							<span class="d-block mt-1"><b>Carl Philip</b></span>
						</div>
					</div>
          <p class="mt-4">
            Très cool ! Je suis mes choix préférés quand je le souhaite et en plus c'est pas cher.
					</p>
				</div>
			</div>
  </div>
</section>

<!-- PARTNERS SECTION  -->
<section class="row justify-content-between my-5">
  <div class="text-center">
    <h2 class="orange_underline">Ils reconnaissent la qualité de nos formations</h2>
    <div class="d-flex justify-content-around mt-5">
      <div class="col-md-2">
        <%= link_to "https://about.google/", :target => "_blank" do %>
          <%= image_tag("google_logo.png", alt:"Logo Google", width: "200") %>
        <%end%>
      </div>
      <div class="col-md-2">
        <%= link_to "https://www.thehackingproject.org/", :target => "_blank" do %>
          <%= image_tag("thp_logo.png", alt:"Logo THP", width: "200") %>
        <%end%>
      </div>
      <div class="col-md-2">
        <%= link_to "https://www.investprep.fr/", :target => "_blank" do %>
          <%= image_tag("Invest_Prep_logo.png", alt:"Formation Private Equity Invest Prep", width: "200") %>
        <%end%>
      </div>
      <div class="col-md-2">
        <%= link_to "https://fr.wikipedia.org/wiki/Mammouth_(hypermarch%C3%A9)", :target => "_blank" do %>
          <%= image_tag("mammouth_logo.png", alt:"Logo Mammouth", width: "200") %>
        <%end%>
      </div>
    </div>
  </div>
</section>