config/routes.rb
Rails.application.routes.draw do
root to: 'static_pages#home'

  devise_for :users
  
  scope "/dashboard" do
    get "admin", to: "dashboard#admin", as: "dashboard_admin"
    get "student", to: "dashboard#student", as: "dashboard_student"
    get "mentor", to: "dashboard#mentor", as: "dashboard_mentor"
  end
  
  resources :dashboard, :themes, :chapters, :courses, :quizzes, :question_answers, :groups, :seasons, :memberships, :user_theme_seasons

  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'fees', to: 'static_pages#fees'
  post 'contact', to: 'static_pages#contact_form', as: 'contact_form'

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
    get "success", to: "checkout#success", as: "checkout_success"
  end

end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :theme
  has_many :courses
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :chapter
  has_one :quiz
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :users, through: :user_groups      # Users as Students > members of the group
  belongs_to :season
  belongs_to :user       #Mentor
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user

  # ActionMailer callback after "Membership" creation to:
  # - send a "welcome message" to the Student
  # - inform the Admin a new Student as subscribe a yearly membership
  after_create :membership_send
  after_create :admin_send

  def membership_send
    UserMailer.membership_email(self).deliver_now
  end

  def admin_send
    UserMailer.admin_email(self).deliver_now
  end
  
end

app/models/question_answer.rb
class QuestionAnswer < ApplicationRecord
  belongs_to :quiz
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :course
  has_many :question_answers
end

app/models/season.rb
class Season < ApplicationRecord
  belongs_to :theme
  has_many :groups
  has_many :user_seasons
  has_many :users, through: :user_seasons
  has_many :user_theme_seasons

  def is_started?
    self.start_date < Time.now()
  end
  
  def is_ended?
    self.end_date < Time.now()
  end

  def is_joinable?
    self.is_started? && !self.is_ended?
  end

  def start_in?
    days = self.start_date - Time.now()
    days.to_i / 60 / 60 / 24
  end

end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :seasons
  has_many :chapters
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:student, :mentor, :admin]
  after_initialize :set_default_role, :if => :new_record?

  has_many :user_seasons
  has_many :seasons, through: :user_seasons

  # Return the role of a given "User" object
  def what_role?
    return self.role
  end

  private

  def set_default_role
    self.role ||= :student
  end

end

app/models/user_season.rb
class UserSeason < ApplicationRecord
  belongs_to :season
  belongs_to :user 
end

app/models/users_group.rb
class UsersGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/utsc_course.rb
class UtscCourse < ApplicationRecord
  belongs_to :user_theme_season_chapter
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/quizes_helper.rb
module QuizesHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnIt!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <%= javascript_include_tag 'application' %>
    
    <!-- Adding STRIPE javascript library needed by the new payment form model -->
    <script src="https://js.stripe.com/v3/"></script>

    <%= favicon_link_tag asset_path('books.png') %>
  </head>
  <body>  
    <%= render("layouts/partials/header") %>  <!-- Including the "header" partial, i.e. a sticky navbar with "Learn It!" logo -->
    
    <main class="container-fluid">            <!-- Adding a "main" container taking all the width of the page -->
      <%= yield %>
    </main>
    
    <%= render("layouts/partials/footer") %>  <!-- Including the "footer" partial -->
  </body>
</html>

app/views/layouts/partials/_add_theme_card.html.erb
<%# Add theme card %>
<div class="col-md-4 col-lg-3"> 
  <div class="card bg-primary text-light h-100">
    <div class="card-body">
      <div class="d-flex flex-column justify-content-center align-items-center h-100">
        <div class="card-text">
          <p class="text-center m-0">Apprenez toujours</p>
        </div>
        <div class="card-text my-3 opacity-75">
          <%= link_to themes_path, class: 'btn btn-outline-secondary rounded-circle' do %>
            <i class="bi bi-plus fs-1"></i>
          <%end%>
        </div>
        <div class="card-text">
          <p class="text-center m-0">avec Learnit!</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/partials/_chapter_card.html.erb
<!-- Chapter horyzontal card used in "chapters" only (local var: my_chapter) -->
<div class="col-5 bg-primary rounded-start ms-2 my-2 p-1">
  <div class="row p-2">
    <div class="col-md-4 col-lg-3">
      <% chapter_logo = "chapters_logos/#{my_chapter.theme.title}/chapter_#{my_chapter.id}.svg"  %>
      <%= image_tag(chapter_logo, alt: "Logo du chapitre", class: "img-fluid") rescue image_tag("SVG_Logo.svg", alt: "Logo du chapitre", class: "img-fluid") %>
    </div>
    <div class="col-md-5 col-lg-6 d-flex flex-column align-items-start">
      <p class="text-light fw-bold"><%= my_chapter.title %> (<%= my_chapter.id %>)</p>
      <p class="text-light fst-italic"><%= my_chapter.content %></p>
    </div>
  </div>
</div>
<div class="col-2 bg-secondary text-center rounded-end me-2 my-2 p-1">
  <div class="row d-flex flex-column">
    <div class="col-4 ms-3 me-auto mt-3 mb-auto">
      <%= link_to("Editer", edit_chapter_path(my_chapter.id), class:"btn btn-sm btn-blue_violet") %>
    </div>
    <div class="col-4 mx-auto my-auto">
      <%= link_to("Créer", new_chapter_path, class:"btn btn-sm btn-light_pulpit") %>
    </div>
      <div class="col-4 ms-auto me-3 mt-auto mb-3">
        <%= link_to("Suppr.", chapter_path(my_chapter.id), method: "delete", class:"btn btn-sm btn-danger", data: {confirm: "Etes-vous certain(e) de vouloir effacer le chapitre n°#{my_chapter.id} : '#{my_chapter.title}' ?"}) %>
    </div>
  </div>
</div>

app/views/layouts/partials/_course_card.html.erb
<!-- Course horyzontal card used in "chapters" only (local var: my_chapter) -->
<div class="col-5 bg-primary rounded-start ms-2 my-2 p-1">
  <p class="text-light fw-bold"><%= my_course.title %> (<%= my_course.id %>)</p>
  <p class="text-light fst-italic"><%= my_course.content %></p>
</div>
</div>
<div class="col-2 bg-secondary text-center rounded-end me-2 my-2 p-1">
  <div class="row">
    <div class="col-4">
      <%= link_to("Editer", edit_course_path(my_course.id), class:"btn btn-sm btn-blue_violet") %>
    </div>
    <div class="col-4">
      <%= link_to("Créer", new_course_path, class:"btn btn-sm btn-light_pulpit") %>
    </div>
      <div class="col-4">
        <%= link_to("Suppr.", course_path(my_course.id), method: "delete", class:"btn btn-sm btn-danger", data: {confirm: "Etes-vous certain(e) de vouloir effacer le cours n°#{my_course.id} : '#{my_course.title}' ?"}) %>
    </div>
  </div>
</div>

app/views/layouts/partials/_course_content.html.erb
<div class="my-3"> 
  <h2><%= course.title %></h2>
  <p><%= course.content %></p>
</div>

app/views/layouts/partials/_dashboard_banner.html.erb
<section class="row-cols-1 bg-primary py-3">
  <div class="container bg-light rounded p-3">
    <div class="row">
      <div class="col-md-3">
        <h5 class="orange_underline">Thème</h5>
        <div id="theme_infos">
          <ul class="list-unstyled">
            <li class=""><%= Theme.find(uts_infos.theme_id).title %></li>
          </ul>
        </div>
      </div>
      <div class="col-md-3">
        <h5 class="orange_underline">Saison</h5>
        <div id="season_infos">
          <ul class="list-unstyled">
            <li class=""><%= Season.find(uts_infos.season_id).name %></li>
          </ul>
        </div>
      </div>
      <div class="col-md-3">
        <h5 class="orange_underline">Mon groupe de travail</h5>
        <div id="group_infos">
          <% members = UsersGroup.where(group_id: Group.where(season_id: uts_infos.season_id))%>
          <ul class="list-unstyled">
            <% members.each do |member| %>
              <li class=""><%= User.find(member.user_id).first_name%> <%=User.find(member.user_id).last_name.upcase %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="col-md-3">
        <h5 class="orange_underline">Mon mentor</h5>
        <div id="mentor_infos">
          <%mentor = Group.find(uts_infos.season_id)%>
          <ul class="list-unstyled">
            <li>
              <%= User.find(mentor.user_id).first_name %> <%= User.find(mentor.user_id).last_name.upcase %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/partials/_flash.html.erb
<div class="row justify-content-center">
  <% flash.each do |type, message| %>
    <div class="col-md-4">
      <div class="alert alert-<%=type%> alert-dismissible" role="alert">
        <%= message %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/partials/_header.html.erb
<header>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div class="container-fluid">
      
      <!-- BEGIN ~ Logo retrieved through the Asset Pipeline -->
      <%= link_to(root_path, class:"navbar-brand ms-3 me-5", method:"get") do %>
        <%= image_tag("learnit_logo_black.png", height:"60px", alt:"LearnIt! - Logo of THE peer-learning web site that condensates the best of all worlds!") %>
      <% end %>
      <!-- END ~ Logo -->

      <!-- BEGIN ~ Hamburger menu toggle icon -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- END ~ Hamburger menu toggle icon -->

      <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
        
        <!-- BEGIN ~ Main menu options and links to static pages: "Cursus", "Tarifs", "A propos de..." and "Contact" -->
        <div class="ms-5">
          <ul class="navbar-nav">
            <li class="nav-item mx-2">
              <%= link_to(themes_path, class:"nav-link", method:"get") do %>
                <i class="bi bi-mortarboard-fill fs-5"> Cursus</i>
              <% end%>
            </li>
            <% if !user_signed_in? %>
            <li class="nav-item mx-2">
              <%= link_to(fees_path, class:"nav-link", method:"get") do %>
                <i class="bi bi-piggy-bank-fill fs-5"> Tarifs</i>
              <% end %>
            </li>
            <% end %>
            <li class="nav-item mx-2">
              <%= link_to(about_path, class:"nav-link", method:"get") do%>
                <i class="bi bi-info-circle-fill fs-5"> A propos de...</i>
              <% end %>
            </li>
            <li class="nav-item mx-2">
              <%= link_to(contact_path, class:"nav-link", method:"get") do %>
                <i class="bi bi-send-fill fs-5"> Contact</i>
              <% end %>
            </li>
            <li>
          </ul>
        </div>
        <!-- END ~ Main menu options and links to static pages -->

        <!-- BEGIN ~ Right part of the navbar: display changes depending of current user connection status  -->
        <div class="ms-5">
          <ul class="navbar-nav">
          <!-- If user is connected, then display "log out" and "go to profile" buttons -->
          <% if !user_signed_in? %>
            <li class="nav-item dropstart">
              <a class="btn btn-secondary rounded-circle me-3" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="bi bi-box-arrow-in-right fs-5"></i>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li>
                  <%= link_to("Sign-in",new_user_session_path, class:"dropdown-item", method:"get") %>
                </li>
                <li>
                  <%= link_to("Sign-up",new_user_registration_path, class:"dropdown-item", method:"get") %>
                </li>
              </ul>
            </li>
          <!-- If user is NOT connected, then display the "log in" (door) button with its dropdown items "sign-in" and "sign-up" -->
          <% else %>
            <li>
              <%= link_to(destroy_user_session_path, class:"btn btn-danger rounded-circle mx-2", method:"delete") do %>
                <i class="bi bi-box-arrow-left fs-5"></i>
              <% end %>
            </li>
            <li class="nav-item dropstart">
              <a class="btn btn-primary rounded-circle ms-2 me-3" href="#" id="navbarDropdown2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="bi bi-person-square fs-5"></i>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown2">
              <% if !current_user.first_name.nil? && !current_user.last_name.nil? %>
                <li>
                  <span class="dropdown-item orange_underline">
                    <i class="bi bi-chevron-double-right text-secondary"></i>
                    <%= current_user.first_name.capitalize %> <%= current_user.last_name.upcase%>
                    <i class="bi bi-chevron-double-left text-secondary"></i>
                  </span>
                </li>
                <li><hr class="dropdown-divider"></li>
              <% end %>
                <li>
                  <%= link_to(dashboard_index_path, class:"dropdown-item", method:"get") do %>
                    <i class="bi bi-speedometer"></i> Tableau de bord
                  <% end %>
                </li>
                <li>
                  <%= link_to(edit_user_registration_path, class:"dropdown-item", method:"get") do %>
                    <i class="bi bi-person-rolodex"></i> Profil utilisateur
                  <% end %>
                </li>
              </ul>
            </li>
          <% end %>
          </ul>
        </div>
        <!-- END ~ Right part of the navbar -->
      
      </div>

    </div>

  </nav>

</header>

app/views/layouts/partials/_hero_banner_index.html.erb
<section class="row py-5 mb-5 bg-primary">
    <div class="col-md-6 text-center"> 
        <%= image_tag("banner_index.jpg", alt:"Photo de startupeurs", class:"img-fluid", width:"500") %>
    </div>
    <div class="col-md-6">
        <h1 class="text-secondary ">LearnIt!</h1>
        <h2 class="text-light">La nouvelle plateforme web d'apprentissage</h2>
        <p class="text-light lead fs-4">
            <%if current_user %>
            <%= current_user.first_name %>, suivez
            <%end%> 
            Vos règles, Votre rythme, Votre communauté !
        </p>
        <div class="row">
        <div class="col-md-8 d-flex justify-content-center pt-5">
            <%if !user_signed_in? %>
                <%= link_to("S'inscrire",new_user_registration_path, class:"btn btn-outline-secondary btn-lg text-light mx-3", method:"get") %>
                <%= link_to("Se connecter",new_user_session_path, class:"btn btn-outline-secondary btn-lg text-light mx-3", method:"get") %>
            <%end%>
        </div>
        </div>
    </div>
</section>

app/views/layouts/partials/_hero_banner_learnit.html.erb
<div class="row justify-content-center">
  <div class="row text-center rounded-bottom" style="background-image: url('<%= asset_path('''Learn_computer.jpg''') %>'); background-size: cover;">
     <div class="col mx-auto mb-5 py-2">
        <h2 class="fs-3 mt-5">Développez vos compétences dans un grand nombre de domaines</h2>
        <h1 class="display-2 fw-bold text-primary my-3">Learn it</h1>
        <div class="mt-4 gap-2 d-sm-flex justify-content-sm-center">
          <% if !user_signed_in? %>
          <%= link_to("S'inscrire",new_user_registration_path,class:"btn btn-warning px-4") %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/layouts/partials/_homepage_theme_card.html.erb
<div class="col-md-4 col-lg-3 mb-3"> 
  <div class="card bg-primary text-light">
    <%= image_tag('code_bg.jpg', alt: "Background code theme card", class: 'card-img-top') %>
    <div class="card-body mt-2">
      <h5 class="card-title"><%= theme.theme.title %></h5>
      <p class="card-text my-4">
        Un cursus de <%= theme.theme.chapters.length %> modules.</br>
        <%= theme.theme.content.truncate(60,separator:" ") %>
      </p>

      <p class="card-text-infos">Plus d'infos</p>
    </div>
    <div class="card-footer">
    <div class="d-flex justify-content-between align-items-center">
      <div id="arrow" class="col-4">
        <%= link_to themes_path do %>
          <i class="bi bi-caret-right-fill fs-1 text-secondary"></i>
        <%end%>
      </div>
      <div id="session_infos" class="col-8">
        <span class="align-middle">Prochaine session dans <%= theme.start_in? %> jours</span>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/layouts/partials/_side_bar_courses.html.erb
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="px-sm-2 px-0 bg-primary">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto nav-link link-light text-decoration-none">
                    <span class="fs-5 d-none d-sm-inline">Menu</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    
                    <% @courses.each do |x_course| %>
                        <li class="nav-item">
                            <%= link_to course_path(x_course.id), method: "get" do %>
                                <i class="fs-5 bi-grid link-light"></i> <span class="ms-1 d-none d-sm-inline link-light"><%= x_course.title %></span>
                            <% end %>
                        </li>
                    <% end %>
                
                </ul>
                <hr>
            </div>
        </div>

    </div>
</div>

app/views/layouts/partials/_user_chapter_card.html.erb
<%# Chapter horyzontal card %>
<div class="col-10 bg-primary">
  <div class="row">
    <div class="col-md-4 col-lg-3">
      <div class="image p-5">
        <% chapter_logo = "chapters_logos/#{chapter.theme.title}/chapter_#{chapter.id}.svg"  %>
          <%= image_tag(chapter_logo, alt: "Logo du chapitre", class: 'img-fluid') rescue image_tag('SVG_Logo.svg', alt: "Logo du chapitre", class: 'img-fluid') %>
      </div>
    </div>
    <div class="col-auto d-flex flex-column justify-content-center align-items-start">
      <h4 class="text-light"><%=  chapter.title %></h4>
      <p class="text-light"><%=  chapter.content %></p>
    </div>
  </div>
</div>
<div class="col-2">
  <div class="d-flex flex-column justify-content-center align-items-center bg-neon_carrot h-100">
    <p class="fs-1"><%= UserThemeSeasonChapter.find(chapter.id).completion_rate %> %</p>
    <%my_courses = UtscCourse.where(user_theme_season_chapter_id: UserThemeSeasonChapter.find(chapter.id)).first %>
    <%if my_courses.nil?%>
      <p>Pas de cours</p>
    <%else%>
      <%= link_to 'Poursuivre', course_path(my_courses), class: 'text-deep_blue' %>
    <%end%>
  </div>
</div>

app/views/layouts/partials/_user_chapters_card_container.html.erb
<%uts_chapter = Chapter.where(theme_id: params[:theme]) %>
  <%uts_chapter.each do |chapter| %>
    <div class="row my-3">
      <%= render 'layouts/partials/user_chapter_card', chapter: chapter %>
    </div>
  <%end %>

app/views/layouts/partials/_user_theme_card.html.erb
<div class="col-md-4 col-lg-3 mb-3"> 
  <div class="card bg-primary text-light h-100">
    <%= image_tag('code_bg.jpg', alt: "Background code theme card", class: 'card-img-top') %>
    <div class="card-body mt-2">
      <h5 class="card-title"><%= theme.title %></h5>
      <p class="card-text my-4">
        Un cursus de <%= theme.chapters.length %> modules.
        <%= theme.content.truncate(60,separator:" ") %>
      </p>
    </div>
    <div class="card-footer border-0">
    <div class="d-flex justify-content-between align-items-center">
      <%if season.is_ended?%>
        <p class="my-3">Session terminée !</p>
      <%elsif season.is_joinable?%>
        <div id="arrow" class="col-4">
          <%= link_to dashboard_student_path+"?theme=#{theme.id}&season=#{season.id}", remote: true do %>
            <i id="theme_<%=theme.id%>" class="bi bi-caret-right-fill fs-1 text-secondary"></i>
          <%end%>
        </div>
        <div id="session_infos" class="col-8">
          <span class="align-middle">Poursuivre</span>
        </div>      
      <%else%>
        <div id="arrow" class="col-4">
          <i id="arrow_button" class="bi bi-clock-history fs-1 text-secondary"></i>
        </div>
        <div id="session_infos" class="col-8">
          <span class="align-middle">Débute dans <%= season.start_in? %> jours</span>
        </div>
      <%end%>
    </div>
    </div>
  </div>
</div>